# Change prefix from 'C-b' to 'C-t'
unbind C-b
set -g prefix C-t
bind C-t send-prefix

# Improve colors
set -g default-terminal "screen-256color"

# Enable mouse support such as scrolling and resizing
set -g mouse on

# Increase scrollback history
set -g history-limit 10000

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows automatically when one is closed
set -g renumber-windows on

# Fix escape-time lag
set -s escape-time 0

# Multiple monitors/resolutions
setw -g aggressive-resize on

# Easy config reload
bind r source-file ~/.config/tmux/tmux.conf